configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hyperspell%2Fhyperspell-f6fece9d5716fd37ebca63185e4e926011974dcef9b76da72afc2f8a0fcec988.yml
openapi_spec_hash: dc4b381a6a2ae7ea6d7ad0d5df10e0e7
config_hash: 4afa3c24db26c8c374eeaf0a739e1b59
