configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hyperspell%2Fhyperspell-d62cfe4e19e8a06c749d20be62ec4d5157be6c1fdbcc1b1daeed7ff74b614eca.yml
openapi_spec_hash: 5442c5ecdba83ac40efaaedaf9a1cd65
config_hash: 63e7969fd7c560b6105e1de79148b568
