configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hyperspell%2Fhyperspell-1ca02322a64dc74cf4ded90d09e6b722aaf69986d2d76bf5aada8567a72ae46f.yml
openapi_spec_hash: b067b13c3b9dd9d7eaf7ba920a8d48fe
config_hash: da009f16a6b9b4db17be2949180ace1e
